# Generated by Django 3.2.13 on 2022-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicsApp_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=150)),
                ('music_logo', models.ImageField(blank=True, upload_to='blog_images')),
                ('music_writer', models.CharField(max_length=500)),
                ('music_singer', models.CharField(max_length=400)),
            ],
        ),
    ]
